# Welcome to Jekyll!

# Site settings
title: "공부기록"
url: "https://yeonhx03.github.io"
locale: "ko-KR"
email: "yeonhx915@gmail.com"
description: >-
  허허허허
github_username: "yeonhx03"
minimal_mistakes_skin: "dark" # 기본 테마는 default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "Asia/Seoul" 

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name     : "이도현" # 좌측 사이드 바 이름
  avatar   : "https://github.com/yeonhx03.png" # github 프로필 사진 연동 # 좌측 사이드 바 프로필 사진
  bio      : "Everything's gonna be Allright" # 좌측 프로필 아래 문구
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yeonhx03"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:yeonhx915@gmail.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yeonhx03"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
